name: Build Azalea and Release
on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build codebase and release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get current unix seconds
        id: unix
        run: |
          echo "value=$(date +'%s')" >> $GITHUB_OUTPUT

      - name: Get version
        id: version
        run: |
          version=$(cat ./extension/manifest.json | grep -oE '[ ]+"version": "(.*)",' | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
          echo "value=$version" >> $GITHUB_OUTPUT
        
      - name: Install dependencies
        id: dependencies
        run: |
          npm i -g pnpm
          pnpm i

      - name: Build codebase
        id: build
        run: pnpm build

      - name: Compress `dist` directory
        id: compress
        run: |
          mv dist Azalea-${{ steps.version.outputs.value }}
          zip -r Azalea.zip Azalea-${{ steps.version.outputs.value }} & wait $!;

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          tag_name: azalea-${{ steps.unix.outputs.value }}
          name: "Azalea ${{ steps.version.outputs.value }}"
          files: ./*.zip